# -*- coding: utf-8 -*-
"""
DeepSeek Credential Grabber
============================
Opens Chrome, waits for you to log in, then auto-captures:
  - Authorization: Bearer <token>
  - All cookies (as a single string)
  - x-device-id from localStorage

Saves them to credentials.txt AND prints them for easy copy.

Author : Ximanta
GitHub : https://github.com/realximanta
Email  : realximanta@gmail.com
License: MIT
"""

import subprocess, sys, os, json, time

# ---------- AUTO-INSTALL ----------
def _ensure(pkg):
    try:
        __import__(pkg)
    except ImportError:
        print(f"[setup] Installing '{pkg}'...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", pkg, "--quiet"]
        )

_ensure("undetected-chromedriver")
_ensure("selenium")

import undetected_chromedriver as uc

# ================== CONFIG ==================
LOGIN_TIMEOUT = 600       # 10 minutes to log in
OUTPUT_FILE   = "credentials.txt"
# ============================================


def launch_and_grab():
    print("=" * 62)
    print(" DeepSeek Credential Grabber — by Ximanta")
    print("=" * 62)

    print("\nLaunching Chrome...")
    options = uc.ChromeOptions()
    options.add_argument("--start-maximized")
    options.set_capability("goog:loggingPrefs", {"performance": "ALL"})

    try:
        driver = uc.Chrome(options=options)
    except Exception as e:
        print(f"\n[ERROR] Failed to launch Chrome: {e}")
        print("Try closing all Chrome windows first.")
        sys.exit(1)

    driver.get("https://chat.deepseek.com")

    print("\n" + "=" * 62)
    print("  👉 Log in to DeepSeek in the opened Chrome window.")
    print("  The script will grab your credentials automatically")
    print("  once you're logged in. Timeout: 10 minutes.")
    print("=" * 62 + "\n")

    token = None
    start = time.time()

    while time.time() - start < LOGIN_TIMEOUT and not token:
        # Sniff performance logs for the Authorization header
        try:
            logs = driver.get_log("performance")
            for entry in logs:
                try:
                    msg = json.loads(entry["message"])["message"]
                    if msg.get("method") == "Network.requestWillBeSent":
                        headers = (msg["params"]["request"]
                                   .get("headers", {}))
                        for k, v in headers.items():
                            if (k.lower() == "authorization"
                                    and str(v).startswith("Bearer ")):
                                token = v
                                break
                    if token:
                        break
                except Exception:
                    continue
        except Exception:
            pass

        if token:
            print("[OK] Token captured! ✅")
            break

        # Show progress heartbeat
        elapsed = int(time.time() - start)
        if elapsed % 10 == 0:
            print(f"  ... waiting for login ({elapsed}s elapsed)")

        time.sleep(2)

    if not token:
        print("\n[FAIL] Timed out. Did you log in?")
        try:
            driver.quit()
        except Exception:
            pass
        return None

    # Grab cookies
    cookies = driver.get_cookies()
    cookie_str = "; ".join(f"{c['name']}={c['value']}" for c in cookies)
    print(f"[OK] Cookies captured ({len(cookies)} items) ✅")

    # Grab x-device-id from localStorage
    device_id = ""
    try:
        device_id = driver.execute_script(
            "return localStorage.getItem('x-device-id') || "
            "localStorage.getItem('device_id') || '';"
        ) or ""
    except Exception:
        pass
    print(f"[OK] x-device-id: {device_id or '(not found, using default)'} ✅")

    try:
        driver.quit()
    except Exception:
        pass

    return token, cookie_str, device_id


def save_credentials(token, cookie_str, device_id):
    """Write credentials to file and print them nicely."""
    content = (
        "# DeepSeek Credentials\n"
        "# Generated by get_credentials.py\n"
        "# ⚠️ DO NOT COMMIT THIS FILE TO GIT!\n\n"
        f"AUTHORIZATION = \"{token}\"\n\n"
        f"COOKIE = \"{cookie_str}\"\n\n"
        f"X_DEVICE_ID = \"{device_id}\"\n"
    )

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print("\n" + "=" * 62)
    print(" 🔑 CREDENTIALS CAPTURED")
    print("=" * 62)
    print(f"\n📄 Saved to: {os.path.abspath(OUTPUT_FILE)}\n")
    print("─" * 62)
    print("AUTHORIZATION:")
    print(f"  {token[:80]}...")
    print("\nCOOKIE:")
    print(f"  {cookie_str[:80]}...")
    print("\nX_DEVICE_ID:")
    print(f"  {device_id}")
    print("─" * 62)
    print("\n📋 Next steps:")
    print("  1. Open deepseek_backup.py")
    print("  2. Copy the 3 values above into the CONFIG block")
    print("  3. Run: python deepseek_backup.py")
    print("\n⚠️  Keep credentials.txt private. Never push to GitHub.")


def main():
    result = launch_and_grab()
    if not result:
        sys.exit(1)
    token, cookie_str, device_id = result
    save_credentials(token, cookie_str, device_id)


if __name__ == "__main__":
    main()